version: '3'

services:
  app:
    build: .

    depends_on:
      - db
      - redis
    
    environment:
      - POSTGRES_ENGINE=django.db.backends.postgresql_psycopg2
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - 8000:8000
  
  db:
    image: postgres:9.6
    environment:
     - POSTGRES_DB=myproject
     - POSTGRES_USER=myprojectuser
     - POSTGRES_PASSWORD=password

    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
  
  redis:
    image: redis:5.0.5-alpine
    